config/routes.rb
FoodIaauEduKg::Application.routes.draw do
  
	resources :dinings
	resources :canteens

  match '/about',       to: 'static_pages#about',     via: 'get'
  match '/home',        to: 'static_pages#home',  		 via: 'get'

 
 
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/canteen.rb
class Canteen < ActiveRecord::Base
  attr_accessible :title, :info, :cost, :imag
end

app/models/dining.rb
class Dining < ActiveRecord::Base
  attr_accessible :day, :first, :second, :firstimage, :secondimage
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/canteens_controller.rb
class CanteensController < InheritedResources::Base

  
  def index
    @canteens = Canteen.all
  end
end

app/controllers/dinings_controller.rb
class DiningsController < InheritedResources::Base
def index
    @dinings = Dining.all
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contacts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/canteens/index.html.erb
<% provide(:title, "Canteen") %>
<div id="<%= "canteen" if params[:controller] == "canteens" %>">
  <div class="bckgrnd-grid">
      <% @canteens.each do |canteen| %>
        <div class="row grid">
            <div class="col-sm-6 col-md-4">
              <div class="thumbnail canteen-container">
                <a href="#" class="thumbnail">
                  <img data-src=<%= link_to (image_tag (canteen.imag), {:class=> "list-img"} ),canteen %>
                </a>
                  <div class="c-d-text">
                      <span class="db_title"><%= canteen.title %></span>
                      <p>
                          <span class="db_capt">
                            Info:
                          </span>
                            <span><%= canteen.info %></span><br/>
                          <span class="db_capt">
                            Cost:
                          </span>
                          <span style="font-weight: bold"><%= canteen.cost %><span class="glyphicon glyphicon-usd" style="font-size: 16px"></span><br/></span>
                      </p>
                  </div>
              </div>
            </div>
         </div>
       <% end %>
  </div>
</div>

app/views/dinings/index.html.erb
<% provide(:title, "Dinning") %>
<div id="<%= "dining" if params[:controller] == "dinings" %>">

  <div class="bckgrnd-grid">
      <% @dinings.each do |dining| %>
          <div class="row grid">
            <div class="col-sm-6 col-md-4">
              <div class="thumbnail dinning-container">
                 <div class="c-d-text">

                      <span class="db_title"><%= dining.day %></span><br/>
                     <div>
                       <div class="first-second">
                         <span class="db_capt">First:</span>
                             <p><%= dining.first %></p>
                             <p><a href="#" class="thumbnail dinning-thumb">

                               <img data-src=<%= link_to (image_tag (dining.firstimage) ),dining %>
                               </a></p>
                       </div>

                       <div>
                         <span class="db_capt">Second:</span>
                            <p><%= dining.second %></p>
                            <p><a href="#" class="thumbnail dinning-thumb">

                              <img data-src=<%= link_to (image_tag (dining.secondimage) ),dining %>
                            </a></p>
                       </div>
                     </div>
                   <div>
                     <span class="db_capt">Tea:</span>
                        <p><a href="#" class="thumbnail dinning-thumb">
                            <%= image_tag ("tea.jpg")%></a>
                        </p>
                   </div>
                     <span class="db_capt">
                            Price: <span class="db_title">50som</span>
                     </span>

                 </div>
              </div>
            </div>
          </div>
      <% end %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li>
        <button class="cnop" data-toggle="modal" data-target="#myModal">
          Contacts
        </button>
        <!-- Modal -->
        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content" style="height: auto">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Contacts</h4>
              </div>
              <div class="modal-body">
                <!-- contact body -->
                <h1>How to find us:</h1>
                <div style="display: inline-flex">
                  <div style="text-align: center">
                    <h4>International Ataturk Alatoo University, Ankara Street 1/8, Tunguch, 720048, Bishkek, Kyrgyz Republic</h4>
                    <p>Tel: +996 (312) 631425</p>
                    <p>Fax: +996(312) 630409</p>
                    <p>E-mail: info@iaau.edu.kg</p>

                  </div>

                  <iframe width="640" height="480" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com.ua/maps?f=q&amp;source=s_q&amp;hl=ru&amp;q=%D0%B0%D1%82%D0%B0%D1%82%D1%8E%D1%80%D0%BA+%D0%B0%D0%BB%D0%B0%D1%82%D0%BE%D0%BE&amp;aq=&amp;sll=42.863383,74.688578&amp;sspn=0.036741,0.084543&amp;ie=UTF8&amp;t=m&amp;st=105250506097979753968&amp;rq=1&amp;ev=zi&amp;split=1&amp;radius=2.57&amp;hq=%D0%B0%D1%82%D0%B0%D1%82%D1%8E%D1%80%D0%BA+%D0%B0%D0%BB%D0%B0%D1%82%D0%BE%D0%BE&amp;hnear=&amp;cid=8080465324218303913&amp;ll=42.863886,74.683428&amp;spn=0.030198,0.054932&amp;z=14&amp;iwloc=A&amp;output=embed"></iframe><br />
                  <small><a href="https://maps.google.com.ua/maps?f=q&amp;source=embed&amp;hl=ru&amp;q=%D0%B0%D1%82%D0%B0%D1%82%D1%8E%D1%80%D0%BA+%D0%B0%D0%BB%D0%B0%D1%82%D0%BE%D0%BE&amp;aq=&amp;sll=42.863383,74.688578&amp;sspn=0.036741,0.084543&amp;ie=UTF8&amp;t=m&amp;st=105250506097979753968&amp;rq=1&amp;ev=zi&amp;split=1&amp;radius=2.57&amp;hq=%D0%B0%D1%82%D0%B0%D1%82%D1%8E%D1%80%D0%BA+%D0%B0%D0%BB%D0%B0%D1%82%D0%BE%D0%BE&amp;hnear=&amp;cid=8080465324218303913&amp;ll=42.863886,74.683428&amp;spn=0.030198,0.054932&amp;z=14&amp;iwloc=A" style="font-size:40px;"><span class="glyphicon glyphicon-fullscreen" "></span></a></small>
                  </div>
                <!--/ contact body -->
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>

              </div>
            </div><!-- /.modal-content -->
          </div><!-- /.modal-dialog -->
        </div><!-- /.modal -->
      </li>




      <li><!-- Button trigger modal -->
        <button class="cnop" data-toggle="modal" data-target="#myModal1">
         News
        </button>

        <!-- Modal -->
        <div class="modal fade" id="myModal1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel1" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel1">IAAU News</h4>
              </div>
              <div class="modal-body">
                <iframe style="width: 100%; height: 100%;" src="http://www.iaau.edu.kg/view/public/news/news.xhtml;jsessionid=k6qVEDFFk-kZQFaoRyYM1ypO.undefined?id=725"> </iframe>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>

              </div>
            </div><!-- /.modal-content -->
          </div><!-- /.modal-dialog -->
        </div><!-- /.modal -->
      </li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!--<a class="navbar-brand" href="#">Bootstrap theme</a>-->
      <%= image_tag ("brand.png"),{:class => 'brand'} %>
      <%= link_to "FOOD IAAU", home_path, class: "navbar-brand none-undr", id: "logo" %>
    </div>

    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right non-unrd">
        <li class="divider"></li>
        <li id="<%= "selected" if params[:controller] == "canteens" %>"> <%= link_to "Canteen",{:controller => 'canteens'} %></li>
        <li class="divider"></li>
        <li id="<%= "selected" if params[:controller] == "dinings" %>"><%= link_to "Dining",{:controller => 'dinings'}%></li>
        <li class="divider-vertical"></li>
        <li id="<%= "selected" if current_page?(about_path) %>"><%= link_to "About", about_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Sign In<b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li>

              <%= link_to "Admin","/admin", target: "_blank"%></li>


            <li class="divider"></li>
            <li><a href="#">Log Out</a></li>
          </ul>
        </li>


    </div><!--/.nav-collapse -->
  </div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> | Food IAAU</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body style="
        background-image: url('assets/background.jpg');
        background-repeat: repeat;
        ">
    <%= render 'layouts/header' %>
    <div class="logo_bckrnd">
      <%= image_tag ("food_logo.png"),{:class => 'logo'} %>
    </div>
    <div class="jumbotron container theme-showcase">
       <div class="jumbotron" style=" background-color: #e9e8eb;">
             <%= yield %>
       </div>
        <%= render 'layouts/footer' %>
    </div>
</body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>

<div>
  <h1 style="margin-top: -30px"><strong>About us</strong></h1>
  <p style="font-family: garamond;
          font-size: 25px;text-align: center;">
    This web site was created by COM-10 student's.
  </p>



    <div class="panel-group" style="text-align: center;" id="accordion">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h4 class="panel-title">
            <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
              PETR GLADUNOV
            </a>
          </h4>
        </div>
        <div id="collapseOne" class="panel-collapse collapse ">
          <div class="panel-body">
            <div class="img-cont">
              <%= image_tag ("petr.jpg"),{:class => 'img'} %>
            </div>
            <div class="abt-text">
                <h3">Project Manager(Developer): Ruby Coder + Data base</h3>
            </div>
            <p>some text</p>
          </div>
        </div>
      </div>
      <div class="panel panel-default">
        <div class="panel-heading">
          <h4 class="panel-title">
            <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
              NURBEK SYDYKOV
            </a>
          </h4>
        </div>
        <div id="collapseTwo" class="panel-collapse collapse">
          <div class="panel-body">
            <div class="img-cont">
              <%= image_tag ("nurbek.jpg"),{:class => 'img'} %>
            </div>
            <div class="abt-text">
              <h3">HTML : CSS Designer</h3>
            </div>
            <p>some text</p>
          </div>
        </div>
      </div>
      <div class="panel panel-default">
        <div class="panel-heading">
          <h4 class="panel-title">
            <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
              ABBAS FATULLAEV
            </a>
          </h4>
        </div>
        <div id="collapseThree" class="panel-collapse collapse">
          <div class="panel-body">
            <div class="img-cont">
              <%= image_tag ("abbas.jpg"),{:class => 'img'} %>
            </div>
            <div class="abt-text">
              <h3">Javascript: Bootstrap</h3>
            </div>
            <p>some text</p>
          </div>
        </div>
      </div>
      <div class="panel panel-default">
        <div class="panel-heading">
          <h4 class="panel-title">
            <a data-toggle="collapse" data-parent="#accordion" href="#collapseFour">
              AZIRET SAPARBEKOV
            </a>
          </h4>
        </div>
        <div id="collapseFour" class="panel-collapse collapse">
          <div class="panel-body">
            <div class="img-cont">
              <%= image_tag ("aziret.jpg"),{:class => 'img'} %>
            </div>
            <div class="abt-text">
              <h3">Test : Testing + Content Managing</h3>
            </div>
            <p>some text</p>
          </div>
        </div>
      </div>
    </div>




</div>

app/views/static_pages/home.html.erb
<% provide(:title, 'Iaau Food') %>
<div>
  <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->

    <ol class="carousel-indicators">
      <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
      <li data-target="#carousel-example-generic" data-slide-to="1"></li>
      <li data-target="#carousel-example-generic" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner">
      <div class="item active">
        <img src="assets/reklam1.jpg">
        <div class="carousel-caption">
          <h3>International Alatoo-Ataturk University</h3>
        </div>
      </div>
      <div class="item ">
        <img src="assets/reklam2.jpg" >
        <div class="carousel-caption">
          <h3>New Year</h3>
        </div>
      </div>
      <div class="item ">
        <img src="assets/reklam3.jpg" >
        <div class="carousel-caption">
          <h3>IAAU</h3>
        </div>
      </div>

    </div>

    <!-- Controls -->
    <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
    </a>
    <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
    </a>
  </div>
 </div>